---
- name: Configlet upload management
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    configlet_dir_var: 'configlets/'
    configlets_prefix_var: 'ASE'
  tasks:
    - name: 'upload configlets to cloudvision {{inventory_hostname}}'
      import_role:
        name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: '{{ configlet_dir_var }}'
        configlets_cvp_prefix: '{{ configlets_prefix_var }}'
