---

- name: Gather device state information
  eos_command:
    commands: "{{ fabric_validation_commands }}"
  register: device_state
  tags:
    - fabric_validation
    - config

- name: Generate yaml output to use for PyTest
  template:
    src: fabric_yaml_output.j2
    dest: ./post_validation/state_outputs/duts_state.yaml
  delegate_to: localhost
  run_once: true
  tags:
    - fabric_validation
    - config

- name: Generate json output to use for PyTest
  template:
    src: fabric_json_output.j2
    dest: ./post_validation/state_outputs/duts_state.json
  run_once: true
  tags:
    - fabric_validation
    - config
