all:
  children:

# DC1_Fabric - EVPN Fabric running in home lab
    AVD_LAB:
      children:
        enterprise_servers:
          hosts:
            srv01:
            localhost:
        # LAB CVP
        CVP:
          hosts:
            AVD-CVP-1:
       # DC1 Fabric
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                DC1-SPINE1:
                DC1-SPINE2:
            DC1_L3LEAFS:
              children:
                DC1_LEAF1:
                  hosts:
                    DC1-LEAF1A:
                DC1_LEAF2:
                  hosts:
                    DC1-LEAF2A:
                    DC1-LEAF2B:
                DC1_SVC3:
                  hosts:
                    DC1-SVC3A:
                    DC1-SVC3B:
                DC1_BL1:
                  hosts:
                    DC1-BL1A:
                    DC1-BL1B:
            DC1_L2LEAFS:
              children:
                DC1_L2LEAF4:
                  hosts:
                    DC1-L2LEAF4A:
                DC1_L2LEAF5:
                  hosts:
                    DC1-L2LEAF5A:
                    DC1-L2LEAF5B:
                DC1_L2LEAF6:
                  hosts:
                    DC1-L2LEAF6A:
                    DC1-L2LEAF6B:

          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: admin
            # should use vault for passwords - leaving un-encrypted for ease of sharing for labs
            ansible_ssh_pass: arista123
            ansible_become: yes
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false

        DC1_TENANTS_NETWORKS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS:
        DC1_SERVERS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS: